import {CONFIG,FLAVOUR_RETURN} from './config.js';import {UPGRADES,RELICS,upgradeCost} from './upgrades.js';import {RITUALS} from './rituals.js';import {ACHIEVEMENTS} from './achievements.js';import {loadGame,saveGame,exportSave,importSave,resetSave} from './save.js';import {render} from './render.js';import {drawTank} from './visuals.js';import {clamp,fmt,pick} from './utils.js';
let state=loadGame(), last=performance.now(), saveTimer=0, renderTimer=0, renderDirty=true, dPress=0; const canvas=document.getElementById('tankCanvas');
function addLog(x){state.log.push(x); if(state.log.length>80)state.log.shift()} function toast(x){const t=document.createElement('div');t.className='toast';t.textContent=x;document.getElementById('toastHost').append(t);setTimeout(()=>t.remove(),3500)}
function lvl(id){return state.upgrades[id]||0} function rel(id){return state.relics[id]||0} function multAll(){return state.worldShell?2:1}
function feedCost(){let c=CONFIG.base.feedCost*Math.pow(1.12-rel('inheritedAppetite')*.006,state.moultCount); c*=Math.pow(.9,lvl('cheapSardines')); return Math.max(3,Math.floor(c));}
function feedGrowth(){let g=CONFIG.base.feedGrowth*(1+lvl('blessedLeftovers')*.1)*(1+rel('sacredChitin')*.15)*(1+lvl('moonlitFeeding')*.6); if(state.resources.hunger>80)g*=.5; if(state.resources.hunger<30)g*=1.1; if(state.rituals.active.brineBlessing)g*=1.3; g*=1+Math.floor(state.resources.madness/100)*.05; return g*multAll();}
function bucketGain(){return (CONFIG.base.bucketGain+lvl('biggerBucket')*10)*(1+lvl('braverFishermen')*.25)*multAll();}
function income(){let roles=state.cult.roles; let fish=(roles.Fishers*.7+lvl('trawlerFleet')*5+lvl('autoBucket')*bucketGain()*.2)*(1+lvl('braverFishermen')*.25); let faith=(state.cult.followers*.2+roles.Acolytes*.8+lvl('firstFollower')+lvl('cellarShrine')*.1)*(1+lvl('candleShrine')*.2+lvl('cellarShrine')*.1+rel('dreamsShell')*.2); let offerings=(state.cult.followers*.08+lvl('cellarShrine')*.4)*(1-Math.min(.35,state.cult.suspicion/1000)); let depth=(lvl('deepGate')*1)*(1+lvl('abyssalTrawler')*.35+rel('deepShell')*.25); let madness=lvl('dreamNet')*.3; if(state.rituals.active.chantBucket)fish*=1.5; if(state.rituals.active.harbourProcession)offerings*=2; if(state.rituals.active.tideLooksBack)depth*=2; if(state.rituals.active.lowerTankDreams){fish*=1.5;faith*=1.5;depth*=1.5;madness+=3;} if(lvl('abyssalTrawler'))fish*=1+lvl('abyssalTrawler')*.35; let madBoost=1+Math.floor(state.resources.madness/100)*.05; faith*=madBoost; return {fish:fish*multAll(),faith:faith*multAll(),offerings:offerings*multAll(),depth:depth*multAll(),madness:madness*multAll()};}
function applyPassive(sec, offline=false){const inc=income(); let off=offline?(1+lvl('nightFeeder')*.15+state.cult.roles.Keepers*.03):1; for(const k of ['fish','faith','offerings','depth','madness']){state.resources[k]+=inc[k]*sec*off;} state.stats.totalDepth+=inc.depth*sec*off; state.stats.totalMadness+=inc.madness*sec*off; state.stats.totalFish+=inc.fish*sec*off; if(offline)return inc;}
function tick(dt){applyPassive(dt); let hunger=CONFIG.base.hungerPerSecond*(1-lvl('tankScrubber')*.1-rel('hardenedHunger')*.08-state.cult.roles.Scrubbers*.03); if(state.rituals.active.quietGlass)hunger*=.6; hunger*=1+Math.floor(state.resources.madness/100)*.02*(1-rel('holyCarapace')*.1); state.resources.hunger=clamp(state.resources.hunger+hunger*dt,0,100); for(const map of [state.rituals.active,state.rituals.cooldowns]) for(const k in map){map[k]-=dt;if(map[k]<=0)delete map[k];} if(state.settings.autoFeed&&lvl('autoFeed')){state.autoTimer=(state.autoTimer||0)+dt; let interval=Math.max(.8,5-lvl('autoFeed')*.7); interval*=1-rel('relicGlass')*.05; if(state.autoTimer>=interval){state.autoTimer=0; feed(true)}} if(Math.random()<dt*.01)addLog(pick(CONFIG.stages[state.stage-1].flavour)); checkUnlocks(); checkStage(); checkAchievements();}
function feed(auto){let c=feedCost(); if(state.resources.fish<c)return false; state.resources.fish-=c; state.resources.growth+=feedGrowth(); if(!state.overgrowth)state.resources.growth=Math.min(100,state.resources.growth); else state.resources.growth=Math.min(300,state.resources.growth); state.maxGrowthThisMoult=Math.max(state.maxGrowthThisMoult,state.resources.growth); state.resources.hunger=clamp(state.resources.hunger-CONFIG.base.feedHunger,0,100); state.stats.feeds++; if(!auto){floatText('+growth'); if(Math.random()<.35)addLog(pick(CONFIG.stages[state.stage-1].flavour));} if(state.resources.growth>=100)addLog('Harold’s shell has begun to crack.'); return true;}
function shellGain(){return Math.max(1,Math.floor((state.maxGrowthThisMoult/100)*(1+state.moultCount*.15)*(1+rel('firstCrack')*.12)*(state.rituals.active.thirdCandle?1.5:1)));}
function moult(){if(state.resources.growth<100)return; let gain=shellGain(); state.resources.shell+=gain; state.stats.totalShell+=gain; state.moultCount++; state.maxGrowthThisMoult=0; state.resources.growth=0; state.resources.hunger=20; state.resources.fish=Math.floor(state.resources.fish*Math.min(.5,rel('lobsterRemembers')*.05))+rel('memoryShell')*100; addLog(`The shell cracks. ${fmt(gain)} Shell remains warm in the damp.`); checkStage(); state.tabs.push('Moult','Relics','Evolution'); state.tabs=Array.from(new Set(state.tabs));}
function buy(id,relic=false){ if(relic){let u=RELICS.find(x=>x.id===id), l=state.relics[id]; let c=u.cost*(l+1); if(l>=u.maxLevel||state.resources.shell<c)return; state.resources.shell-=c; state.relics[id]++; addLog(`${u.name} is pressed into the reliquary.`); return;} let u=UPGRADES.find(x=>x.id===id), l=state.upgrades[id], c=upgradeCost(u,l), type=u.costType; if(type==='faith'&&u.fallbackType&&state.resources.faith<c){type='fish'; c*=5;} if(l>=u.maxLevel||state.resources[type]<c)return; state.resources[type]-=c; state.upgrades[id]++; if(id==='firstFollower')state.cult.followers++; if(id==='deepGate')state.tabs.push('Evolution'); if(id==='dreamNet')addLog('Madness is now a measurable resource. This seems bad.'); addLog(`${u.name} improves the operation.`); checkUnlocks();}
function performRitual(id){let r=RITUALS.find(x=>x.id===id); if(!r||state.rituals.cooldowns[id])return; for(const [k,v] of Object.entries(r.cost)) if((state.resources[k]||0)<v)return; for(const [k,v] of Object.entries(r.cost)) state.resources[k]-=v; state.rituals.active[id]=r.duration; if(r.cooldown)state.rituals.cooldowns[id]=r.cooldown; if(id==='harbourProcession')state.cult.followers+=3+state.cult.roles.Choristers; if(id==='lowerTankDreams')state.resources.madness+=100; if(['ninthMoult','openWorldTank','feedMoon','crackReality'].includes(id))state.finalChain[id]=true; if(id==='lastShell'){state.endingSeen=true;state.worldShell=true;showEnding();} addLog(`Ritual performed: ${r.name}.`);}
function checkStage(){let s=state; let next=true; while(next&&s.stage<10){next=false; if(s.stage===1&&s.moultCount>=1)next=true; else if(s.stage===2&&s.moultCount>=3&&s.stats.totalShell>=3)next=true; else if(s.stage===3&&s.moultCount>=5&&s.cult.followers>=5)next=true; else if(s.stage===4&&s.moultCount>=8&&income().faith>=10)next=true; else if(s.stage===5&&s.moultCount>=12&&lvl('harbourShrine'))next=true; else if(s.stage===6&&s.moultCount>=16&&s.stats.totalDepth>=1000)next=true; else if(s.stage===7&&s.moultCount>=22&&s.stats.totalDepth>=5000&&lvl('dreamNet'))next=true; else if(s.stage===8&&s.moultCount>=30&&s.stats.totalMadness>=10000)next=true; else if(s.stage===9&&s.moultCount>=40&&state.finalChain.crackReality)next=true; if(next){s.stage++; addLog(`Evolution: Harold becomes ${CONFIG.stages[s.stage-1].name}.`); toast(`Evolution: ${CONFIG.stages[s.stage-1].name}`);}}
 state.overgrowth=s.stage>=4; checkUnlocks();}
function checkUnlocks(){if(state.resources.growth>=20&&state.cult.followers===0&&lvl('firstFollower')===0){state.cult.followers=1;state.upgrades.firstFollower=1;addLog('A damp stranger appoints themself First Follower. Softlock avoided.');} if(state.cult.followers>0)state.tabs.push('Cult'); if(state.moultCount>0)state.tabs.push('Moult','Relics','Evolution'); if(state.stage>=4||state.moultCount>=5)state.tabs.push('Rituals'); state.tabs=Array.from(new Set(state.tabs));}
function checkAchievements(){for(const a of ACHIEVEMENTS) if(!state.achievements[a.id]&&a.test(state)){state.achievements[a.id]=Date.now();toast(`Achievement: ${a.name}`);}}
function offline(){let elapsed=Math.min(CONFIG.base.offlineCapSeconds,Math.max(0,(Date.now()-(state.lastSave||Date.now()))/1000)); if(elapsed>60){let before={...state.resources}; applyPassive(elapsed,true); addLog(`${FLAVOUR_RETURN} Away ${Math.floor(elapsed/60)}m: +${fmt(state.resources.fish-before.fish)} Fish, +${fmt(state.resources.offerings-before.offerings)} Offerings, +${fmt(state.resources.faith-before.faith)} Faith, +${fmt(state.resources.depth-before.depth)} Depth, +${fmt(state.resources.madness-before.madness)} Madness.`)}}
function floatText(txt){let f=document.createElement('div');f.className='float';f.textContent=txt;document.getElementById('floatLayer').append(f);setTimeout(()=>f.remove(),900)}
function showEnding(){document.getElementById('modalHost').className='modal-host';document.getElementById('modalHost').innerHTML=`<div class="modal"><h2>The World Becomes A Tank</h2><p>“The final shell cracks. The sky peels away in one wet piece. Somewhere beneath the last ocean, the Lobster opens its eyes and finds the world small enough to eat.”</p><p>World Shell unlocked: all production ×2. Endless mode continues.</p><button id="closeModal">Continue</button></div>`;document.getElementById('closeModal').onclick=()=>document.getElementById('modalHost').className='modal-host hidden'}
function responsive(fn){return (...args)=>{const result=fn(...args); renderDirty=true; return result;}}
const actions={income,feedCost,feedGrowth,bucketGain,shellGain,tab:responsive(t=>state.activeTab=t),bucket:responsive(()=>{const gain=bucketGain();state.resources.fish+=gain;state.stats.bucketClicks++;state.stats.totalFish+=gain;floatText('+'+fmt(gain)+' fish')}),feed:responsive(feed),moult:responsive(moult),buy:responsive(buy),role:responsive((r,d)=>{let assigned=Object.values(state.cult.roles).reduce((a,b)=>a+b,0); if(d>0&&assigned>=state.cult.followers)return; state.cult.roles[r]=Math.max(0,state.cult.roles[r]+d)}),ritual:responsive(performRitual),saveBtn:()=>{saveGame(state);toast('Saved')},exportBtn:()=>document.getElementById('saveText').value=exportSave(state),importBtn:responsive(()=>{state=importSave(document.getElementById('saveText').value);toast('Imported')}),resetBtn:()=>{if(confirm('Reset the cult?')){resetSave();location.reload()}},debugToggle:responsive(()=>state.settings.debug=!state.settings.debug),debug:responsive(k=>{if(k==='fish')state.resources.fish+=1000;if(k==='faith')state.resources.faith+=100;if(k==='shell')state.resources.shell+=10;if(k==='growth')state.resources.growth=95;if(k==='tabs')state.tabs=[...CONFIG.tabs];if(k==='stage')state.stage=Math.min(10,state.stage+1);checkUnlocks();})};
window.addEventListener('keydown',e=>{if(e.key.toLowerCase()==='d'&&++dPress>=3){state.settings.debug=!state.settings.debug;dPress=0;toast('Debug toggled')}}); window.addEventListener('beforeunload',()=>saveGame(state)); if('serviceWorker'in navigator)navigator.serviceWorker.register('service-worker.js').catch(()=>{}); offline();
function loop(now){let dt=Math.min(.2,(now-last)/1000); last=now; tick(dt); saveTimer+=dt; renderTimer+=dt; drawTank(canvas,state,now/1000); if(renderDirty||renderTimer>.2){render(state,actions);renderDirty=false;renderTimer=0} if(saveTimer>CONFIG.base.autosaveSeconds){saveGame(state);saveTimer=0} requestAnimationFrame(loop)} requestAnimationFrame(loop);
