import {CONFIG} from './config.js';import {UPGRADES,RELICS,upgradeCost} from './upgrades.js';import {RITUALS} from './rituals.js';import {ACHIEVEMENTS} from './achievements.js';import {fmt} from './utils.js';import {getStage} from './state.js';
let lastResources='',lastStatus='',lastTabs='',lastPanel='',lastLog='';
function bindPress(el,fn){if(!el)return; let touchHandled=0; const run=e=>{if(el.disabled)return; fn(e); el.blur?.();}; el.addEventListener('pointerup',e=>{if(e.pointerType==='mouse')return; if(e.button!==undefined&&e.button!==0)return; e.preventDefault(); touchHandled=Date.now(); run(e);},{passive:false}); el.addEventListener('click',e=>{if(Date.now()-touchHandled<700){e.preventDefault(); return;} run(e);});}
export function render(state, actions){
 const $=id=>document.getElementById(id), inc=actions.income();
 const resources=['fish','offerings','faith','shell','depth','madness'].map(r=>`${r}:${Math.floor(state.resources[r]||0)}`).join('|');
 if(resources!==lastResources){$('resourceBar').innerHTML=['fish','offerings','faith','shell','depth','madness'].map(r=>`<div class="res ${(state.resources[r]||0)>0?'':'dim'}"><span>${icon(r)}</span><b>${cap(r)}</b><em>${fmt(state.resources[r]||0)}</em></div>`).join(''); lastResources=resources;}
 const st=getStage(state), target=actions.growthTarget(), status=`${state.stage}|${state.moultCount}|${state.overgrowth}|${target}|${state.resources.growth.toFixed(1)}|${state.resources.hunger.toFixed(0)}|${Object.values(inc).map(v=>v.toFixed(2)).join(',')}`;
 if(status!==lastStatus){$('statusCard').innerHTML=`<div><b>${st.name}</b><span>Stage ${state.stage}/10 · Moult ${state.moultCount}</span></div><label>Growth <meter min="0" max="${state.overgrowth?target*3:target}" value="${state.resources.growth}"></meter> ${fmt(state.resources.growth)} / ${fmt(target)}</label><label>Hunger <meter min="0" max="100" value="${state.resources.hunger}"></meter> ${state.resources.hunger.toFixed(0)}/100</label><p>Passive: 🐟 ${fmt(inc.fish)}/s · 🕯 ${fmt(inc.offerings)}/s · ✦ ${fmt(inc.faith)}/s · 🌊 ${fmt(inc.depth)}/s · ☽ ${fmt(inc.madness)}/s</p>`; lastStatus=status;}
 const tabs=`${state.activeTab}|${CONFIG.tabs.map(t=>state.tabs.includes(t)?1:0).join('')}`;
 if(tabs!==lastTabs){$('tabBar').innerHTML=CONFIG.tabs.map(t=>`<button class="tab ${state.activeTab===t?'active':''}" ${state.tabs.includes(t)?'':'disabled'} data-tab="${t}">${state.tabs.includes(t)?'':'🔒 '}${t}</button>`).join(''); $('tabBar').querySelectorAll('button:not([disabled])').forEach(b=>bindPress(b,()=>actions.tab(b.dataset.tab))); lastTabs=tabs;}
 const pKey=panelKey(state,actions); if(pKey!==lastPanel){$('panel').innerHTML=panel(state, actions); wire(state, actions); lastPanel=pKey;}
 const log=state.log.slice(-8).join('|'); if(log!==lastLog){$('logList').innerHTML=state.log.slice(-8).reverse().map(x=>`<p>${x}</p>`).join(''); lastLog=log;}
}
function panelKey(s,a){return JSON.stringify({tab:s.activeTab,up:s.upgrades,re:s.relics,roles:s.cult.roles,followers:s.cult.followers,tabs:s.tabs,growth:Math.floor(s.resources.growth),target:a.growthTarget(),over:s.overgrowth,feed:a.feedCost(),shell:a.shellGain(),auto:s.settings.autoFeed,settings:s.settings,ach:s.achievements,active:Object.fromEntries(Object.entries(s.rituals.active).map(([k,v])=>[k,Math.ceil(v)])),cool:Object.fromEntries(Object.entries(s.rituals.cooldowns).map(([k,v])=>[k,Math.ceil(v)]))});}
function cap(s){return s[0].toUpperCase()+s.slice(1)} function icon(r){return {fish:'🐟',offerings:'🕯',faith:'✦',shell:'🦞',depth:'🌊',madness:'☽'}[r]}
function panel(s,a){ const tab=s.activeTab; if(tab==='Feed')return `<div class="actions"><button id="bucket" class="primary">Haul Fish Bucket<br><small>+${fmt(a.bucketGain())} Fish</small></button><button id="feed" class="danger">Feed Lobster<br><small>Cost ${fmt(a.feedCost())} Fish · +${a.feedGrowth().toFixed(1)}% Growth</small></button></div><label class="toggle"><input id="autoFeedToggle" type="checkbox" ${s.settings.autoFeed?'checked':''} ${s.upgrades.autoFeed?'':'disabled'}> Auto Feed ${s.upgrades.autoFeed?'enabled':'locked'}</label>`;
 if(tab==='Upgrades')return cards(UPGRADES.filter(u=>u.unlock(s)),s,a,false);
 if(tab==='Relics')return `<p>Spend permanent Shell on relics. Relics survive every Moult.</p>`+cards(RELICS,s,a,true);
 if(tab==='Cult')return cult(s,a); if(tab==='Rituals')return rituals(s,a); if(tab==='Moult')return moult(s,a); if(tab==='Evolution')return evolution(s); if(tab==='Achievements')return ACHIEVEMENTS.map(x=>`<article class="card ${s.achievements[x.id]?'bought':''}"><h3>${s.achievements[x.id]?'🏆':'◇'} ${x.name}</h3><p>${x.description}</p></article>`).join(''); return settings(s); }
function cards(list,s,a,relic){return `<div class="cards">${list.map(u=>{let lvl=(relic?s.relics:s.upgrades)[u.id]||0, max=lvl>=u.maxLevel, cost=relic?u.cost*(lvl+1):upgradeCost(u,lvl); let type=relic?'shell':(u.costType==='faith'&&s.resources.faith<cost&&u.fallbackType?'fish':u.costType); if(max)return `<article class="card complete" aria-label="${u.name} complete"><h3>✓ ${u.name}</h3><p>Complete · Level ${lvl}/${u.maxLevel}</p></article>`; return `<article class="card"><h3>${u.name}</h3><p>${u.description}</p><p>Level ${lvl}/${u.maxLevel}</p><button data-buy="${u.id}" data-relic="${relic?1:0}">Buy: ${fmt(cost)} ${cap(type)}</button></article>`}).join('')}</div>`}
function cult(s){let assigned=Object.values(s.cult.roles).reduce((a,b)=>a+b,0), free=s.cult.followers-assigned;return `<p>Followers ${s.cult.followers} · Free ${free} · Devotion ${fmt(s.cult.devotion)} · Suspicion ${fmt(s.cult.suspicion)}</p>${CONFIG.roles.map(r=>`<div class="role"><b>${r}</b><span>${s.cult.roles[r]}</span><button data-role="${r}" data-d="-1">−</button><button data-role="${r}" data-d="1">+</button></div>`).join('')}`}
function rituals(s){return RITUALS.filter(r=>r.unlock(s)).map(r=>{let active=s.rituals.active[r.id],cooldown=s.rituals.cooldowns[r.id],blocked=active||cooldown; return `<article class="card"><h3>${r.name}</h3><p>${r.description}</p><p>${Object.entries(r.cost).map(([k,v])=>`${fmt(v)} ${cap(k)}`).join(' · ')} ${active?` · Active ${active.toFixed(0)}s`:''}${cooldown?` · Cooldown ${cooldown.toFixed(0)}s`:''}</p><button data-ritual="${r.id}" ${blocked?'disabled':''}>Perform</button></article>`}).join('')||'<p>The candles are waiting for worse decisions.</p>'}
function moult(s,a){let target=a.growthTarget(), ready=s.resources.growth>=target; return `<h2>${ready?'Harold’s shell has begun to crack.':'The shell is not ready.'}</h2><p>Moulting resets Growth, lowers Hunger, grants permanent Shell, and may evolve the lobster.</p><p>Growth Required: ${fmt(target)}</p><p>Expected Shell: ${fmt(a.shellGain())}</p><button id="moultBtn" class="danger" ${ready?'':'disabled'}>Moult</button>`}
function evolution(s){return CONFIG.stages.map(st=>`<article class="card ${s.stage>=st.id?'bought':''}"><h3>${st.id}. ${st.name}</h3><p>${st.tone}</p><p>Requirement: ${st.req}</p></article>`).join('')}
function settings(s){return `<div class="actions small"><button id="saveBtn">Save</button><button id="exportBtn">Export Save</button><button id="importBtn">Import Save</button><button id="resetBtn">Reset Save</button></div><textarea id="saveText" placeholder="Export/import save text"></textarea><label><input id="animToggle" type="checkbox" ${s.settings.animations?'checked':''}> Animations</label><label><input id="motionToggle" type="checkbox" ${s.settings.reducedMotion?'checked':''}> Reduced motion</label><label><input id="soundToggle" type="checkbox" ${s.settings.sound?'checked':''}> Sound placeholder</label><button id="debugToggle">Show Debug Controls</button>${s.settings.debug?`<div class="debug"><button data-debug="fish">+1,000 Fish</button><button data-debug="faith">+100 Faith</button><button data-debug="shell">+10 Shell</button><button data-debug="growth">Growth 95%</button><button data-debug="tabs">Unlock tabs</button><button data-debug="stage">Advance stage</button></div>`:''}`}
function wire(s,a){const press=bindPress;press(document.getElementById('bucket'),a.bucket);press(document.getElementById('feed'),()=>a.feed(false));document.getElementById('autoFeedToggle')?.addEventListener('change',e=>s.settings.autoFeed=e.target.checked);press(document.getElementById('moultBtn'),a.moult);document.querySelectorAll('[data-buy]').forEach(b=>press(b,()=>a.buy(b.dataset.buy,b.dataset.relic==='1')));document.querySelectorAll('[data-role]').forEach(b=>press(b,()=>a.role(b.dataset.role,Number(b.dataset.d))));document.querySelectorAll('[data-ritual]').forEach(b=>press(b,()=>a.ritual(b.dataset.ritual)));['saveBtn','exportBtn','importBtn','resetBtn','debugToggle'].forEach(id=>{let el=document.getElementById(id); if(el) press(el,a[id])});['animToggle','motionToggle','soundToggle'].forEach(id=>{let el=document.getElementById(id); if(el) el.onchange=e=>{s.settings[id.replace('Toggle','').replace('anim','animations').replace('motion','reducedMotion')]=e.target.checked}});document.querySelectorAll('[data-debug]').forEach(b=>press(b,()=>a.debug(b.dataset.debug)));}
